services:
  app:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - postgres
    ports:
      - "3005:3000"
    networks:
      - webscrapper
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
    env_file: .env.docker
    environment:
      RAILS_ENV: development
      BASE_URL: http://localhost:3005
      POSTGRES_DATABASE: webscrapper
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432

  postgres:
    image: postgres:16.2
    restart: always
    ports:
      - "5435:5432"
    networks:
      - webscrapper
    environment:
      POSTGRES_PASSWORD: 123456
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  gem_cache:
  db_data:

networks:
  webscrapper:
    driver: bridge